#pragma config(Sensor, S2,     MSMMUX,         sensorI2CCustom)
#pragma config(Motor,  motorA,          scoopMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: mindsensors-motormux-test1.c 133 2013-03-10 15:15:38Z xander $
 */

/**
 * mindsensors-motormux.h provides an API for the Mindsensors Motor MUX. This program
 * demonstrates how to use that API to control the motors attached to the MUX.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to Mindsensors for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * 05 April 2010
 * version 0.1
 */

#include "drivers/mindsensors-motormux.h"

#include "JoystickDriver.c"
task main()
{
	// initialize the motor mux
	MSMMUXinit();
	// Reset the encoders.
  	MSMMotorEncoderResetAll(MSMMUX);
	// Reset the encoders for our specific motor too
	// we are using Sensor Port 2, Motor Mux Port 2 for our arm control
  	MSMMotorEncoderReset(mmotor_S2_2);

  	// These are actually the default values for the PID controller
  	MSMMUXsetPID(MSMMUX, 0x1B58, 0x0000, 0x927C, 0x3A98, 0x012c, 0x1D4C, 0x10, 0x80);

  	// set the brake method
  	MSMMotorSetBrake(mmotor_S2_2);

  	// set initial motor state to stopped
	MSMotorStop(mmotor_S2_2);
  
  	while(true)
	{
		alive();
		// obtain the joystick values
		getJoystickSettings(joystick);

		// -35 to +35 is our stick deadzone to prevent motor creeping at small values
		// joy1_y1 is the controller for the left set of wheels
		if(joystick.joy1_y1 < 35 && joystick.joy1_y1 > -35) {
			motor[motorC] = 0;
		}
		else{
			motor[motorC] = joystick.joy1_y1;
		}

		// joy1_y2 is the controller for the right set of wheels
		if(joystick.joy1_y2 < 35 && joystick.joy1_y2 > -35) {
			motor[motorB] = 0;
		}
		else{
			motor[motorB] = joystick.joy1_y2;
		}

		// joy1_TopHat is the left d-pad
		// -1 means no button being pushed
		if(joystick.joy1_TopHat == -1) {
			motor[motorA] = 0;
		}
		// 0 means that "up" is being pushed
		else if(joystick.joy1_TopHat == 0) {
			motor[motorA] = -25;
		}
		// 4 means that "down" is being pushed
		else if (joystick.joy1_TopHat == 4) {
			motor[motorA] = 25;
		}

		// joy1Btn(2) is the Y button on the controller to move the arm down
		if (joy1Btn(2)) {
			MSMMotor(mmotor_S2_2, -127);
			//PlaySound(soundUpwardTones);
		}
		// joy1Btn(4) is the A button on the controller to move the arm up
		else if (joy1Btn(4)) {
			MSMMotor(mmotor_S2_2, 127);
			//PlaySound(soundDownwardTones);
		}
		// stop the arm motor at all other times
		else {
			MSMotorStop(mmotor_S2_2);
			//ClearSounds();
  		}
	}
}